### ISSUE TITLE
Default `double_quotes` flag should be `chars`

### ISSUE THREAD

**Issue by ichiban** [ichiban/prolog#183]
https://github.com/ichiban/prolog/issues/176#issuecomment-1075505151

The current default is `codes`, which follows GNU Prolog.

https://github.com/ichiban/prolog/blob/f2029460f9a56e751e3d1e27f06a68448012460e/engine/parser.go#L628

**Comment by ichiban** [comment]
The ISO standard says the default value is implementation defined.

> 7.11.2.5 Flag: double-quotes
> 
> Possible values: chars, codes, atom
> 
> Default value: implementation defined
> 
> Changeable: Yes

**Comment by guregu** [comment]
I like `chars` as a default. @triska's lesson on DCGs outlines a good argument for using it. Alignment with Scryer and Tau is also nice.
https://www.metalevel.at/prolog/dcg
