### ISSUE TITLE
Error reporting , number_chars/2

### ISSUE THREAD

**Issue by UWN** [ichiban/prolog#192]
[#13](http://www.complang.tuwien.ac.at/ulrich/iso-prolog/number_chars#13):

```
?-  number_chars(N,[a|a]). 
2022/04/08 21:55:12 error(type_error(list, a), 'Expected list, found engine.Atom.') % unexpected
```
Expected: type_error(list, [a|a]).

To make errors more uniform, it helps a lot to express them internally in two ways: must_be(Type, X) and can_be(Type, X). See e.g. library(error) of Scryer. In above case, the entire term has to be reported. with can_be(list, [a|a]) you get this automatically.

(Also note that a dot in a list is not recognized just as in [#1](http://www.complang.tuwien.ac.at/ulrich/iso-prolog/number_chars#1))

**Comment by UWN** [comment]
Maybe a clarification for [this table](http://www.complang.tuwien.ac.at/ulrich/iso-prolog/number_chars) which was created in preparation of Cor.2. What you need to conform to is Section 0 and Section 2. In Section 1 the sorry state prior to Cor.2 is depicted..

**Comment by UWN** [comment]
@ichiban: one question on this: how do I go-wise update and recompile?  ((For rust I say: `git pull && cargo build --release` and for C mostly `git pull && make`))

**Comment by ichiban** [comment]
@UWN Thank you very much for letting me know the problems! `git pull && go install github.com/ichiban/prolog/cmd/1pl` will recompile and install `1pl` from the source code.

Note that `go install github.com/ichiban/prolog@latest` will install the latest release of `1pl`. Without a version suffix, it recompiles and install from the source code.

```console
MacBook-Air:prolog ichiban$ git pull
Already up to date.
MacBook-Air:prolog ichiban$ go install github.com/ichiban/prolog/cmd/1pl
MacBook-Air:prolog ichiban$ $(go env GOPATH)/bin/1pl
Top level for ichiban/prolog (devel)
This is for testing purposes only!
See https://github.com/ichiban/prolog for more details.
Type Ctrl-C or 'halt.' to exit.
?- 
```

Alternatively, you can `git pull && go run cmd/1pl/main.go` to run without installing it.

```console
MacBook-Air:prolog ichiban$ git pull
Already up to date.
MacBook-Air:prolog ichiban$ go run cmd/1pl/main.go 
Top level for ichiban/prolog (devel)
This is for testing purposes only!
See https://github.com/ichiban/prolog for more details.
Type Ctrl-C or 'halt.' to exit.
?- 
```

**Comment by UWN** [comment]
[Here](http://www.complang.tuwien.ac.at/ulrich/iso-prolog/draft-number_chars-errors) is the draft for the corrections of Cor.2 for the errors of `number_chars/2`, so you can see all error clauses at the same time.

**Comment by ichiban** [comment]
@UWN I'm sorry for not being clear! To `git pull`, you need to make a working copy first:

```console
$ cd ~/src                                                   # Or anywhere you work with code.
$ git clone git@github.com:ichiban/prolog.git ichiban-prolog # Creates a working copy in ~/src/ichiban-prolog.
$ cd ichiban-prolog
$ git pull
Already up to date.
$ go install github.com/ichiban/prolog/cmd/1pl               # Installs 1pl from this working copy.
```

I think this is the fastest way to do `git pull && go install github.com/ichiban/prolog/cmd/1pl`.

Alternatively, you can fork `github.com/ichiban/prolog` first and make a working copy of it. It's a preferred way to make a pull request: https://github.com/ichiban/prolog#contributing

The files under `~/go/pkg/mod` must be the cached files to build the `1pl` command from `go install github.com/ichiban/prolog/cmd/1pl@latest`.

**Comment by UWN** [comment]
Or, how can I cleanly uninstall it? Such that I can just install it anew? I tried SO for this, but did not get any go-related good answer. Maybe I messed up something. But for other systems, everything is fine.

**Comment by UWN** [comment]
Thank you, finally, I have everything in place. I will close this now, to make sure that issues remain related to one clear topic.
