### ISSUE TITLE
Undetected integer overflow, incorrect syntax

### ISSUE THREAD

**Issue by UWN** [ichiban/prolog#201]
```
?- X is 2^63. 
X = --9223372036854775808; % unexpected
?- X is 2^63,writeq(X).
--9223372036854775808X = --9223372036854775808 % unexpected
```

**Comment by ichiban** [comment]
When it prints out a negative integer, the current implementation first flips the sign then prints out a `-` followed by the positive integer. My hunch is that the problem is in this procedure of writing a negative integer. I'll consult the standard document and fix it.

**Comment by UWN** [comment]
In branch fix-integer-power:

```
?- current_prolog_flag(bounded,T).
T = true;
?- current_prolog_flag(max_integer,V).
V = 9223372036854775807;
?- X is 2^63.
2022/05/02 09:32:24 error(evaluation_error(int_overflow), 'Integer overflow.')
?- X is 2^62-1+2^62.
X = 9223372036854775807;
?- X is 2^62-1+2^62+1.
2022/05/02 09:32:37 error(evaluation_error(int_overflow), 'Integer overflow.')
```
Perfect!

**Comment by ichiban** [comment]
Thank you very much! As you implied in the title, there were 2 problems: one is that on the edge case, the output was incorrect and the other is the implementation of `^/2` is incorrect and couldn't detect integer overflow.
