### ISSUE TITLE
Support call_nth/2

### ISSUE THREAD

**Issue by UWN** [ichiban/prolog#202]
<a href="http://www.complang.tuwien.ac.at/ulrich/iso-prolog/call_nth">This predicate</a> is particularly useful for testing purposes.

**Comment by Jean-Luc-Picard-2021** [comment]
Why not ask for change_arg/3. You can bootstrap a lot
of usuful think with change_arg/3 alone. Here is my take
on call_nth/2 as done for Dogelog Player:
```
/**
 * call_nth(G, C):
 * The predicate succeeds whenever G succeeds and unifies C with
 * the numbering of the successes.
 */
% call_nth(+Goal, -Integer)
call_nth(G, C) :- var(C), !,
   call_nth2(G, N),
   C = N.
call_nth(G, C) :-
   C > 0,
   call_nth2(G, N),
   (C =:= N -> !; fail).

% call_nth2(+Goal, -Integer)
call_nth2(G, N) :-
   Holder = v(0),
   G,
   arg(1, Holder, M),
   N is M+1,
   change_arg(1, Holder, N).
```

**Comment by Jean-Luc-Picard-2021** [comment]
Ok, you know this implementation anyway,
but nobody promotes change_arg/3, why is this so?

**count the number of calls of a clause**
https://stackoverflow.com/a/11400256/17524790

**Comment by UWN** [comment]
Providing destructive assignment has many negative effects. It results in many implementation dependent effects that practically prevent more advanced techniques. Both statically and dynamically.

Consider the fact
````
f(g(h(c)), h(c)).
````

this might be compiled into

```
f(g(X),Y) :- X=h(c), X = Y.
```

With destructive assignments present, such optimizations change the meaning of programs.

If you look into existing implementations, there are only a few that permit general destructive assignment (SWI), many provide more limited, much better defined forms (SICStus, Eclipse). And some just provide `call_nth/2` like Trealla and Scryer.

Term representation becomes a bit visible when writing unnamed variables (`?- writeq(X-X).`) and in term comparison. With destructive assignment things become much worse.

The easiest way out is just to provide `call_nth/2` and to defer all other considerations to a later moment.

**Comment by Jean-Luc-Picard-2021** [comment]
If you don't think about introducing change_arg/3 in your 
Prolog system first, and start implementing call_nth/2 and all
other stuff instead first, you are doing something wrong.

The design flaw is seen in Scryer Prolog which has a much slower call_nth/2 now:
```
/* Scryer Prolog */
?- time((between(1,1000,_), call_nth(call_nth((X=a;X=b), N), M), fail; true)).
   % CPU time: 1.010s
   true.
```
On the other hand in Dogelog Player I get, and I even don't need
any expensive setup_call_cleanup/3 in its implementation:
```
/* Dogelog Player */
?- time((between(1,1000,_), call_nth(call_nth((X=a;X=b), N), M), fail; true)).
% Wall 61 ms, gc 0 ms, 837475 lips
true.
```
Or as Trump said: "If it works, its not broken". You can mark
the built-in as internal only, and warn the ordinary end-user 
to not use it, until the end-user exactly knows what he is doing.

**Comment by Jean-Luc-Picard-2021** [comment]
Actually Trump said: "Sounds good, doesn't work". But `change_arg/3` 
is exactly the converse. It excels above all!!! In the above Dogelog Player 
is 16 times faster. But I nowhere advocate making change_arg/3 a

novice Prolog programmer predicate. I even don't know whether its
possible in Scryer Prolog or in ichiban/prolog. Also change_arg/3 is
usally simpler to use for atomic Prolog terms than for non-atomic 

Prolog terms. So a strategy could be to first experiment with change_arg/3
that can update atomic replacements. Later things can indeed become
complicated, for example SWI-Prolog has two different copy_term/2.

**Comment by UWN** [comment]
As to SICStus and ECLiPSe, you could see their highly restricted ways providing such functionality in the [link to SO](https://stackoverflow.com/a/11400256) that you posted. They do not provide the generality of setarg. There used to be an (undocumented) setarg in earlier versions of SICStus which was according to the sources "Put in at the express request of" some person. And it only worked for one cons-cell. As for GNU, it does not have garbage collection...

**Comment by Jean-Luc-Picard-2021** [comment]
You wrote:
> you could see their highly restricted ways providing such functionality in the link to SO 

I don't see anything. Its shows the use case call_nth/2. It doesn't not discuss ECLiPSe Prolog even.

**Comment by Jean-Luc-Picard-2021** [comment]
You see what the potential speed is in GNU Prolog:
```
?- ((between(1,1000000,_), call_nth2(call_nth2((X=a;X=b),N), M), fail; true)).
(1578 ms) yes
```
I was using:
```
call_nth2(Goal_0, C) :-
   State = v(0),
   Goal_0,
   arg(1, State, C1),
   C2 is C1+1,
   setarg(1, State, C2, false),
   C = C2.
```

**Comment by ichiban** [comment]
@UWN Thank you for letting me know this! I've learnt that the community hasn't agreed on what `nth` really means in Prolog https://github.com/ichiban/prolog/issues/160#issuecomment-1068351595 so I'll implement `call_nth/2` as an extension and make it available in `1pl`.

**Comment by UWN** [comment]
Looks good, even for [this case](https://github.com/trealla-prolog/trealla/issues/246#issuecomment-903219941). And don't worry, should there be any further error, it will soon appear, because I use `call_nth/2` quite a lot.
