### ISSUE TITLE
go for Ubuntu 14?

### ISSUE THREAD

**Issue by UWN** [ichiban/prolog#203]
When I try to install go on Ubuntu 14 (my preferred old laptop), I get only the message "Requires installation of untrusted packages" and no matter what I say ([OK] or [Repair]) I remain stuck in that state.

(For Rust, everything works quite smoothly)

Is there some way out?

**Comment by ichiban** [comment]
I'm a mac user so I can't say for sure but I found some answer https://askubuntu.com/a/15659 that says trusting the package by adding GPG keys will solve the problem.

If `apt-get` doesn't work, you should be able to install Go from the official site: https://go.dev/doc/install

**Comment by UWN** [comment]
Thank you! https://go.dev/doc/install solved it!
