### ISSUE TITLE
How install on WSL ?

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [ichiban/prolog#204]
When I try on WSL I get:
```
$ go get -u github.com/ichiban/prolog
package embed: unrecognized import path "embed" (import path does not begin with hostname)
package io/fs: unrecognized import path "io/fs" (import path does not begin with hostname)
$
```

**Comment by ichiban** [comment]
@Jean-Luc-Picard-2021 Hi! Both `embed` and `io/fs` are introduced in go1.16. Could you run `$ go version` and see if it's newer than 1.16, please? If it's older, upgrading Go will solve the problem.

**Comment by Jean-Luc-Picard-2021** [comment]
Yes, could be the issue, I am only using go1.10.

**Comment by guregu** [comment]
I'm using WSL2 (Ubuntu 20) and `sudo apt install golang` will get a working version.

```
$ go version
go version go1.18.1 linux/amd64
```

The interpreter itself works great on Windows, but it seems like 1pl can't pick up keyboard input from the Windows terminal. I might take a crack at fixing that.
