### ISSUE TITLE
boundary checking error for builtin arg

### ISSUE THREAD

**Issue by rosbit** [ichiban/prolog#213]
for builtin `arg`,  the ending boundary check for `N`-th doesn't work. 

now the code is written as
```golang
if n == 0 || int(n) >= len(c.Args)
```

it should be
```golang
if n == 0 || int(n) > len(c.Args)
```

**Comment by rosbit** [comment]
```prolog
:- arg(2, buys(john, beer), Arg).
```
expected to `Arg = beer`, but now `false`.

**Comment by ichiban** [comment]
@rosbit Thank you very much for reporting this! I'll fix it.

**Comment by ichiban** [comment]
I merged a fix for this, so It'll be fixed in the next release.
