### ISSUE TITLE
read: missing representation error

### ISSUE THREAD

**Issue by UWN** [ichiban/prolog#216]
Since you have chosen to have bounded integers, also reading must detect overflows correctly:

In branch fix-integer-power
```
?- V = -9223372036854775809.
V = -9223372036854775808. % unexpected
?- V = 9223372036854775809. 
V = 9223372036854775807. % unexpected
```

Both cases require a representation error qua 8.14.1.3 j.

Alternatively, you may opt implementing unbounded integers. However, I'd suggest this only if the Go-environment provides high quality libraries for this purpose (never, ever do this yourself! As a quick check, look at `X is 7^7^7` and `X is 9^9^9` both should complete in reasonable time. That is less than 2 minutes). E.g. Rust has quite performing libraries, not sure about Go.

**Comment by ichiban** [comment]
They're fixed in `v.0.10.0`.

Go has unbounded integers in one of its standard libraries `math/big`, yet it may lack some of the arithmetic functors. I'll keep an eye on the possibilities to support unbounded integers, but for now, it throws representation errors.

```console
$ $(go env GOPATH)/bin/1pl
Top level for ichiban/prolog v0.10.0
This is for testing purposes only!
See https://github.com/ichiban/prolog for more details.
Type Ctrl-C or 'halt.' to exit.
?- V = -9223372036854775809.
2022/07/16 13:46:48 failed to query: error(representation_error(min_integer),root)
?- V = 9223372036854775809.
2022/07/16 13:47:01 failed to query: error(representation_error(max_integer),root)
```
