### ISSUE TITLE
initialization/1: no warning for failing goals

### ISSUE THREAD

**Issue by UWN** [ichiban/prolog#252]
Good that you added the `initialization/1` directive and decided that the implementation defined order in which multiple such directives get executed is just the textual appearance in the file.

Currently however, failing goals do not produce any feedback. Ideally, there is some fitting feedback. Many (if not all) implementations produce a warning for such failing initialization goals.

**Comment by ichiban** [comment]
As of `v0.11.1`, a failed initialization goal raises an error.

```prolog
% init_fail.pl
:- initialization(fail).
:- initialization((write(hi), nl)).
```

```console
$ $(go env GOPATH)/bin/1pl
Top level for ichiban/prolog v0.11.1
This is for testing purposes only!
See https://github.com/ichiban/prolog for more details.
Type Ctrl-C or 'halt.' to exit.
?- [init_fail].
2022/09/19 12:21:03 failed initialization goal: fail
?- 
```

It might be better if it were a warning, but I couldn't find an ideal Go interface for it.

The closest thing is handling of `set_prolog_flag(unknown, warning)` but a user of this library has to set a callback in case of warnings, which is easy to miss.

https://github.com/ichiban/prolog/blob/c0d191821497d7fbf51c4d311ba820adf652abb2/cmd/1pl/main.go#L86

**Comment by UWN** [comment]
Some use the `initialization/1` directive as a testing device. So they would expect this to list of all directives. On the other hand, continuing the initialization process in spite of a failing goal might lead to further problems. At least it seems Ichiban is the first to go this route.

**Comment by UWN** [comment]
Given that you are stopping initialization is case of failure, does it make sense that you are continuing initialization in case of error?

```
ulrich@TU-Wien:/opt/gupu/ichiban-prolog$ cat > init_fail.pl
:- initialization(functor(_,_,_)).
:- write(here), nl.
ulrich@TU-Wien:/opt/gupu/ichiban-prolog$ $(go env GOPATH)/bin/1pl
Top level for ichiban/prolog (devel)
This is for testing purposes only!
See https://github.com/ichiban/prolog for more details.
Type Ctrl-C or 'halt.' to exit.
?- [init_fail].
here
2022/09/19 08:21:11 error(instantiation_error,functor/3)

**Comment by UWN** [comment]
Just for the record: initialization is also stopped for errors which makes sense.

```
ulrich@TU-Wien:/opt/gupu/ichiban-prolog$ cat > init_fail.pl
:- initialization(functor(_,_,_)).
:- initialization((write(here),nl)).
ulrich@TU-Wien:/opt/gupu/ichiban-prolog$ $(go env GOPATH)/bin/1pl
Top level for ichiban/prolog (devel)
This is for testing purposes only!
See https://github.com/ichiban/prolog for more details.
Type Ctrl-C or 'halt.' to exit.
?- [init_fail].
2022/09/19 08:24:38 error(instantiation_error,functor/3)
