### ISSUE TITLE
Empty list ambiguity

### ISSUE THREAD

**Issue by amimart** [ichiban/prolog#296]
## Description

When comparing an empty list `[]` with the `'[]'` atom, it is considered equal.

## How to reproduce

This issue can be easily reproduced using the provided interactive interpreter `cmd/1pl`:

```sh
?- [] = '[]'.
true
```

I'd be happy to have your thoughts about that, if I can be of any help it'll be a pleasure :)

**Comment by pmoura** [comment]
The empty list *is* an atom in ISO Prolog Core standard and in almost all Prolog systems (*). There's no bug here.

(*) The only exception is SWI-Prolog which made the (questionable and very publicly criticized decision) to make `[]` its own type in release 7.x.

**Comment by amimart** [comment]
Oh I see, thanks @pmoura :)
